config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#accueil'
  get 'contacts' => 'static_pages#contacts'
  get 'aide' => 'static_pages#aide' 
  get 'recherche' => 'static_pages#recherche' 
  get 'enseignements' => 'static_pages#enseignements' 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def accueil
  end

  def enseignements
  end

  def recherche
  end 

  def aide
  end

  def contacts
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Département de Physique"
    if page_title.empty?
      base_title
    else  
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Département de Physique - <a href="http://www.univ-ag.fr">Université des Antilles</a>
  </small>
  <nav>
    <ul class="nav navbar-nav pull-right">
      <li><%= link_to "Contacts", contacts_path %></li>
      <li><%= link_to "Aide", aide_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!--header class="navbar navbar-fixed-top navbar-inverse "-->
<header class="navbar navbar-fixed-top navbar-default">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Département de Physique", root_path , id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
        <!--ul class="nav navbar-pills pull-right"-->
          <li><%= link_to "Accueil",        root_path ,class: "active"%></li>
          <li><%= link_to "Recherche",      recherche_path , role: "presentation"%></li>
          <li><%= link_to "Enseignements",  enseignements_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
 </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container jumbotron">
      <%= yield %>
    </div>
  </body>
    <%= render 'layouts/footer' %>
</html>

app/views/static_pages/accueil.html.erb
  <h1>Bienvenue au Département de Physique - Université des Antilles</h1>

  <!--%= link_to "Enregistrez-vous maintenant!", '#', class: "btn btn-lg btn-primary"  %--> 

app/views/static_pages/aide.html.erb
<% provide(:title, 'Aide')  %>
<p> Contacter <%= mail_to 'fbrute@gmail.com', "France-Nor" %> </p>

app/views/static_pages/contacts.html.erb
<% provide(:title, 'Contacts') %>

<p>Secrétariat : 0590 48 31 06</p>

app/views/static_pages/enseignements.html.erb
<% provide(:title, 'Enseignements') %>
<h1> Pourquoi démarrer un parcours en Physique ?</h1>

app/views/static_pages/recherche.html.erb
<% provide(:title, 'Recherche') %>
<h1>Département de Physique - Université des Antilles</h1>
<p>Thématiques de Recherche</p>